language: node_js
node_js:
  - "8"

script:
  - npm test
  - npm run build
  - rm -r node_modules
  - find -not -name 'index.html' -not -name 'static-map.js' -delete

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
